channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.3.1
- pip:
  - mlflow==2.17.0
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
